spring.application.name=replan

spring.datasource.url=jdbc:mysql://localhost:3306/replan_db
spring.datasource.username=${REPLAN_DB_USERNAME}
spring.datasource.password=${REPLAN_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
gemini.api.key=${REPLAN_GEMINI_API_KEY}